bind = , Scroll_Lock, exec, brightnessctl --device='*::scrolllock' set 50%!-
exec-once = brightnessctl --device='*::scrolllock' set 1

# Regra para transformar o btop em um widget flutuante no canto da tela
windowrulev2 = float, class:(sys_widget)
windowrulev2 = size 420 320, class:(sys_widget)
windowrulev2 = move 100%-440 50, class:(sys_widget)
windowrulev2 = pin, class:(sys_widget)
windowrulev2 = noinitialfocus, class:(sys_widget)

# Inicializa o widget junto com o Hyprland (usando o kititty ou alacritty)
exec-once = kitty --class sys_widget -e btop
