general {
    lock_cmd = pidof hyprlock || hyprlock        # evita iniciar multiplas instancias do hyprlock
    # lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock  # pausa players ao travar
    before_sleep_cmd = loginctl lock-session    # trava a sessao antes de suspender
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && (noctalia-cli reload || (killall -9 noctalia; nohup noctalia > /dev/null 2>&1 &))
}

listener {
    timeout = 480                                # 8min.
    on-timeout = brightnessctl -s set 10         # reduz o brilho do monitor ao minimo
    on-resume = brightnessctl -r                 # restaura o brilho do monitor
}

# listener {
#     timeout = 480                                # 8min.
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # desliga o backlight do teclado
#     on-resume = brightnessctl -rd rgb:kbd_backlight        # restaura o backlight do teclado
# }

listener {
    timeout = 600                                # 10min
    on-timeout = loginctl lock-session            # trava a tela apos o tempo limite
}

listener {
    timeout = 660                                # 11min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r && (noctalia-cli reload || (killall -9 noctalia; nohup noctalia > /dev/null 2>&1 &))
}

listener {
    timeout = 1800                               # 30min
    on-timeout = systemctl suspend               # suspende o PC
}
